### ISSUE TITLE
Feature Availability Matrix - Still getting updated? 

### ISSUE THREAD

**Issue by DennstedtB** [Keller-Michael/Eclipse_ADT_info_hub#1]
Hi, 
I just wondered if this blog "[ADT Feature Availability Matrix for AS ABAP Releases](https://blogs.sap.com/2013/06/05/adt-feature-availability-matrix-for-as-abap-releases/)", by Thomas Fiedler, still gets updated? 

If yes it should get into the list. 
Unfortunately I don't have eclipse available right know - So I can't have a look at the release notes of ADT.

**Comment by Keller-Michael** [comment]
I think this blog is still maintained. There is a column for 7.52. I will add it. Thanks for the hint!

**Comment by Keller-Michael** [comment]
Link was added
